# Generated by Django 4.0.4 on 2022-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_name', models.CharField(max_length=30, verbose_name='Имя профиля')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('avatar', models.ImageField(null=True, upload_to='images', verbose_name='Фото профиля')),
            ],
        ),
    ]
