# Generated by Django 4.0.4 on 2022-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя профиля')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
