# Generated by Django 4.0.4 on 2022-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_product_kind_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('Выбор 1', 'Выбор 1'), ('Выбор 2', 'Выбор 2'), ('Выбор 3', 'Выбор 3')], default='Выбор 3', max_length=7, verbose_name='Список'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('citi', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('products', models.ManyToManyField(to='apple.product')),
            ],
        ),
    ]
