# Generated by Django 4.0.4 on 2022-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_alter_product_kind_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('Выбор 1', 'Выбор 1'), ('Выбор 2', 'Выбор 2')], default='Выбор 1', max_length=7, verbose_name='Список'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='citi',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Адресс'),
        ),
    ]
